### ISSUE TITLE
ダイヤル回転時の加算値の符号は逆の方が嬉しい

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SpriteStudio5-SDK#15]
- 時計回りで数値が＋されて時間が進んでいくほうが直感的だなぁと思いました。
- ついでに frame については、EndFrame でクランプされるか、EndFrameに到達したと分かる何かがあると嬉しいです。常に２５０あたりで一周しすべて赤くなるようですが、この値がEndFrameになっていると分かりやすいと思います。

**Comment by DKAlpha** [comment]
こちらは対応予定がありませんのでクローズします。
