### ISSUE TITLE
カラーブレンドのアルファ値が正常に機能していない。

### ISSUE THREAD

**Issue by Kurooka** [SpriteStudio/SpriteStudio5-SDK#46]
カラーブレンドで単色を指定した際に、アルファ値に154を指定するとスプライトが表示されない。

**Comment by Kurooka** [comment]
カラーブレンド値をＸＭＬから取得の際に正数とみなされる場合に失敗していたので修正を行いました。

コミット: 346595dc11ea87a06e9c951c9dc85a0b91e44cf5 [346595d]

**Comment by Kurooka** [comment]
viewerのexeファイルの更新とmasterへの合流は今しばらくお待ちください。

**Comment by Kurooka** [comment]
取り急ぎ修正したwindows版のビューアをdevelopブランチへアップいたしました。
こちらをご使用いただけますと幸いです。

developブランチの直接のダウンロードURLはこちらになります。
https://github.com/SpriteStudio/SpriteStudio5-SDK/archive/develop.zip

**Comment by DKAlpha** [comment]
マスターへ繁栄されましたのでクローズとします。
