### ISSUE TITLE
Converter でパーツ名やセル名が数字だけだとデータが化ける

### ISSUE THREAD

**Issue by RF-mima** [SpriteStudio/SpriteStudio5-SDK#49]
タイトル通りです。
データの確認はcocos2dx v3 の再生モジュールになります。。

**Comment by DKAlpha** [comment]
ご報告ありがとうございます。
名前を数値だけで付けたセル名（例えば「1」「10」など）が存在すると、ssbpへのコンバート時に正常に出力されない現象を確認いたしました。
対応可能か検討しまして、進展がありましたらこちらでご報告されていただいます。

現状での回避策としては、数値とならない名前にしてもらう事で回避する事ができます。
例えば「_0」「cell10」[1_1]などにリネームしていただいて、ssbpのコンバートを行っていただく事で意図した表示がされると思いますので、そちらをお試しいただければと思います。

**Comment by DKAlpha** [comment]
SpriteStudioSDK v1.4.3にてSS5Converterのセル名前が数値の場合に正しくコンバートできない問題を修正しました。
ただし制限としてセル名に「.(ピリオド)」を使用すると正しくコンバートできない問題が確認されていますので、ご注意ください。

**Comment by RF-mima** [comment]
御対応を有り難うございました！
