### ISSUE TITLE
表示状態が変わる Ver.4 互換オプションに対応して欲しい

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SpriteStudio5-SDK#50]
プロジェクトの設定→互換性 にある
1. 親子の座標変換にマトリックスを使用しない(Ver4.互換)
2. 不透明度・反転・非表示アトリビュートの継承方法をVer.4と同様にする。
以上、２つのオプションが、それぞれONの時の表示状態を再現するデータを出力するようにして欲しいです。

各オプションのチェック状態は .sspj ファイルの dontUseMatrixForTransform, rootPartFunctionAsVer4 タグの値として保存されています。

できれば、これを参照し、自動判定して欲しいです。
難しい場合は、コマンドラインオプションで任意に指定する方法でも構いません。

**Comment by DKAlpha** [comment]
SDK v1.4.3にてプロジェクトの互換性設定に応じてssbpを出力する機能が追加されました。
こちらで作成したデータはSS5Player for Cocos2d-xに含まれるv4_developブランチ（https://github.com/SpriteStudio/SS5PlayerForCocos2d-x/tree/v4_develop）に含まれるCocos2d-x v3系プレイヤーみ再生が可能です。
こちらのプレイヤーはVer4互換での再生を完全に保証するものではありません。
今後developブランチの変更が反映される予定もございませんので、その点を了承したうえでご使用ください。
