### ISSUE TITLE
処理速度について質問があります

### ISSUE THREAD

**Issue by tallsally** [SpriteStudio/SpriteStudio5-SDK#59]
Cocos2dx3.8に対応させるため、SpriteStudio5.5に変更しましたところ、処理落ちするようになってしまいました。

以前のバージョン(2015/1頃）に比べて処理が重たくなっているのだと思いますが、ごく簡単な使い方しかしていないので（たとえば親子関係などは使っていません）、もしコメントアウト等でカットできる処理の部分があれば、ご教授願いたいです。

**Comment by DKAlpha** [comment]
SS5Player for cocos2d-xについてのご質問であれば、プレイヤーのIssue（https://github.com/SpriteStudio/SS5PlayerForCocos2d-x/issues）へ投稿していただけると助かります。

**Comment by tallsally** [comment]
プレイヤーのIssueの方へ同様の質問を投稿いたしました。
何卒よろしくお願い致します。

**Comment by DKAlpha** [comment]
お手数をおかけします。
こちらの件は
https://github.com/SpriteStudio/SS5PlayerForCocos2d-x/issues/29
で引き続き対応いたしますので、closeとさせていただきます。
