### ISSUE TITLE
配置したキーのバイナリデータ格納について

### ISSUE THREAD

**Issue by kamiya1234** [SpriteStudio/SpriteStudio5-SDK#63]
いつもお世話になっております。

ssbpLibで扱うバイナリデータですが、キーを配置しても初期キーから変化がない限りバイナリには含まれない認識なのですがこちらをコンバートオプション等の指定で含めるようにする変更は可能でしょうか？

用途としては以下を想定しております。
 Aアニメーション
　　　キー配置なし
 Bアニメーション
　　　0フレーム目にＸ座標を50
　　　10フレーム目にＸ座標を50
　　　20フレーム目にX座標を100

Bアニメーションのキー情報だけを拾い、Ａアニメーションに適応したい場合
今現在だと初期データに50と格納され、フレームデータには11フレーム目まで格納されないのを
キー情報が打ってあれば格納するように変更するイメージです。

あるいは、フレームデータには入れずに、
PART_FLAGに追加していただければこちらでその情報を拾うことができますので
こちらでもご検討をお願いいたします。

何卒ご検討いただけると幸いです。

以上となります。
宜しくお願い致します。

**Comment by DKAlpha** [comment]
ご質問ありがとうございます。
まずssbpの概念からご説明したいと思いますが、「初期キーから変化がない限りバイナリには含まれない認識」という事ですが、こちらは厳密には補間された結果の値が初期値と違う場合にフレームデータに含まれるという事になります。
よってSpriteStudio上で作成したキーが出力されているわけではございません。

例えば0、10、20、30フレームに以下のようにキーを作成した場合、
![default](https://user-images.githubusercontent.com/8114390/28298862-b7068206-6bb0-11e7-8770-2ed5563412aa.png)
11～29までのデータはフレームデータとして出力されます。
フレームデータにはSpriteStudioで作成したキーか補間によって値が変わったフレームかは区別していませんので、SpriteStudioで作成したキーだけ取得したいというのは難しいと思います。

続いて「コンバートオプション等の指定で含めるようにする変更は可能でしょうか？」ですが、コンバータを改造する場合以下のようになるかと思います。
・全フレームのデータをフレームデータに含める
　SpriteStudio上で設定したキーかはわからない、バイナリのサイズが大きくなる
　SpriteStudio上で設定したキーかは新たに何かしらのフラグを付ければ判別できるかもしれない。
・SpriteStudioのキーのみフレームデータに含める
　SpriteStudioのキーである事がわかる。
　プレイヤーでは補間計算は行っておりませんので、全フレーム補間なしの挙動になる。
　
今後プレイヤーでこのようなデータに対応する予定はございませんので、ユーザー様でSDKの方へ改造を行っていただければと思います。

「Bアニメーションのキー情報だけを拾い、Ａアニメーションに適応したい場合」というのが具体的にどういう事か想像できなのですが、おそらく想定外の使い方だと思いますので、SDKまたはプレイヤーをユーザー様で改造していただければと思います。

基本的にフレームデータがない場合は初期値チャンクの値を使用する事で全データ取得できる事になりますので、１１フレームまでは初期値チャンクの値50を参照されるとBの動きを再現できるかと思います。

よろしくお願いいたします。

**Comment by DKAlpha** [comment]
補足しますとアニメーションに特定フレームでトリガーがほしいという事であれば、ユーザーデータを活用する方法もあるかと思います。
こちらの記事も参考になるかもしれません。
· SpriteStudio/SS5PlayerForCocos2d-x
v1.3.0 任意のフレームのユーザーデータを取得したい 
https://github.com/SpriteStudio/SS5PlayerForCocos2d-x/issues/50

**Comment by kamiya1234** [comment]
ご回答ありがとうございます。
諸々承知致しました。

上記方法で実現可能か検討致します。
