### ISSUE TITLE
相対パスで.sspj ファイルを指定できるようにして欲しい

### ISSUE THREAD

**Issue by SpriteStudio** [SpriteStudio/SpriteStudio5-SDK#7]
# 仕様
- コンバータへの入力パスとして相対パスが指定可能
 - e.g.) Ss5Conveter ./ssprojs/HOGE.sspj
- 変換時のパスは常に.sspj 基点とし、これまでと同じ動作になる。

**Comment by DKAlpha** [comment]
こちらは対応予定がありませんのでクローズします。
